### ISSUE TITLE
Fails to install for python 3.7 under Ubuntu 20.04

### ISSUE THREAD

**Issue by DaytonaJohn** [mabu-github/pgimp#12]
Attempted to install using **sudo python3.7 -m pip install pgimp**.  I am developing using python3.7, not python3.8. When I run the above command, I get **ERROR: Failed building wheel for pgimp**.

It appears that python-fu-eval is not found. If I run a command starting with **/usr/bin/gimp -idf --batch-interpreter python-fu-eval**,  it hangs with the message:
**GIMP-Warning: The batch interpreter 'python-fu-eval' is not available. Batch mode disabled.**

Here is the output of the attempted install:

```
Collecting pgimp
  Using cached pgimp-1.0.0a22.tar.gz (140 kB)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.7/site-packages (from pgimp) (1.19.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/site-packages (from pgimp) (5.7.2)
Building wheels for collected packages: pgimp
  Building wheel for pgimp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jb34kpbc/pgimp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jb34kpbc/pgimp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1ht1n8ga
       cwd: /tmp/pip-install-jb34kpbc/pgimp/
  Complete output (122 lines):
  /usr/local/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.0.0-alpha-22' to '1.0.0a22'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/GimpScriptRunner.py", line 381, in _send_to_gimp
      self._gimp_process.communicate(code.encode(), timeout=timeout_in_seconds)
    File "/usr/local/lib/python3.7/subprocess.py", line 964, in communicate
      stdout, stderr = self._communicate(input, endtime, timeout)
    File "/usr/local/lib/python3.7/subprocess.py", line 1716, in _communicate
      self._check_timeout(endtime, orig_timeout, stdout, stderr)
    File "/usr/local/lib/python3.7/subprocess.py", line 1011, in _check_timeout
      stderr=b''.join(stderr_seq) if stderr_seq else None)
  subprocess.TimeoutExpired: Command '['/usr/bin/gimp', '-i', '-d', '-f', '--batch-interpreter=python-fu-eval', '-b', '-']' timed out after 20 seconds
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-jb34kpbc/pgimp/setup.py", line 90, in <module>
      build_py=GimpDocumentationGeneratorCommand
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-jb34kpbc/pgimp/setup.py", line 56, in run
      generate_python_skeleton()
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/doc/GimpDocumentationGenerator.py", line 52, in __call__
      self._document_pdb_module()
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/doc/GimpDocumentationGenerator.py", line 149, in _document_pdb_module
      methods = self._execute(pdb_dump, 20)
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/doc/GimpDocumentationGenerator.py", line 177, in _execute
      return self._gsr.execute_and_parse_json(string, timeout_in_seconds=timeout_in_seconds)
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/GimpScriptRunner.py", line 211, in execute_and_parse_json
      timeout_in_seconds=timeout_in_seconds,
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/GimpScriptRunner.py", line 300, in execute
      parameters=parameters,
    File "/tmp/pip-install-jb34kpbc/pgimp/pgimp/GimpScriptRunner.py", line 384, in _send_to_gimp
      raise GimpScriptExecutionTimeoutException(str(exception) + '\nCode that was executed:\n' + code)
  pgimp.GimpScriptRunner.GimpScriptExecutionTimeoutException: Command '['/usr/bin/gimp', '-i', '-d', '-f', '--batch-interpreter=python-fu-eval', '-b', '-']' timed out after 20 seconds
  Code that was executed:
  # Copyright 2018 Mathias Burger <mathias.burger@gmail.com>
  #
  # SPDX-License-Identifier: MIT
  
  import os
  import sys
  
  import gimp
  
  binary = bool(os.environ['__binary__'])
  stdout_file = os.environ['__stdout__']
  sys.stdout = open(stdout_file, 'w' if not binary else 'wb')
  stderr_file = os.environ['__stderr__']
  sys.stderr = open(stderr_file, 'w')
  
  
  def __exception_hook(exctype, value, traceback):
      sys.__excepthook__(exctype, value, traceback)
      sys.stderr.write('__GIMP_SCRIPT_ERROR__ {:d}'.format(1))
      gimp.pdb.gimp_quit(0)
  
  
  sys.excepthook = __exception_hook
  if '__working_directory__' in os.environ:
      os.chdir(os.environ['__working_directory__'])
  sys.path.append(os.getcwd())
  
  if '__PYTHONPATH__' in os.environ:
      pythonpath = os.environ['__PYTHONPATH__']
      for path_component in [x.strip() for x in pythonpath.split(':')]:
          sys.path.append(path_component)
  
  sys.path.append('/tmp/pip-install-jb34kpbc/pgimp')
  
  from collections import OrderedDict
  from pgimp.gimp.parameter import return_json
  
  result = OrderedDict()
  
  num_matches, procedure_names = pdb.gimp_procedural_db_query("", "", "", "", "", "", "")
  methods = sorted(procedure_names)
  for method in methods:
      blurb, help, author, copyright, date, proc_type, num_args, num_values = pdb.gimp_procedural_db_proc_info(method)
      result[method] = OrderedDict()
      result[method]['blurb'] = blurb
      result[method]['help'] = help
      result[method]['args'] = OrderedDict()
      result[method]['vals'] = OrderedDict()
      for arg_num in range(0, num_args):
          arg_type, arg_name, arg_desc = pdb.gimp_procedural_db_proc_arg(method, arg_num)
          if arg_name == 'run-mode':
              continue
          result[method]['args'][arg_name] = OrderedDict()
          result[method]['args'][arg_name]['type'] = arg_type
          result[method]['args'][arg_name]['desc'] = arg_desc
      for val_num in range(0, num_values):
          val_type, val_name, val_desc = pdb.gimp_procedural_db_proc_val(method, val_num)
          result[method]['vals'][val_name] = OrderedDict()
          result[method]['vals'][val_name]['type'] = val_type
          result[method]['vals'][val_name]['desc'] = val_desc
  
  return_json(result)
  
  pdb.gimp_quit(0)
  ----------------------------------------
  ERROR: Failed building wheel for pgimp
```
Environment:
    OS: Ubuntu 20.04
    Python:
         python3.8 installed (/usr/bin/python3 is linked to /usr/bin/python3.8)
         python3.7 installed as /usr/local/bin/python3.7 (/usr/bin/python3.7 is linked to /usr/local/bin/python3.7)
         python2 installed as /usr/bin/python2.7 (/usr/bin/python2 is linked to /usr/bin/python2.7)
    gimp: gimp-2.10

**Comment by mugimugi555** [comment]
Me too.
I'm a beginner, so I don't know, but I got the same error on a clean install of Ubuntu.

The page I referred to is here.

[ Python , Gimp ] pgimp (Python-fuを少し使いやすくするツール) を Windows で使う – あきばこ工房 
https://akibakokoubou.jp/2020/01/04/python-gimp-pgimp-gimp%E3%82%92python%E5%81%B4%E3%81%8B%E3%82%89%E4%BD%BF%E3%81%86%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA-%E3%82%92-windows-%E3%81%A7%E4%BD%BF%E3%81%86/

How to Install Python Pip on Ubuntu 20.04 | Linuxize 
https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/

I hope they fix it.

**Comment by EisbarGFX** [comment]
Can still reproduce today, a long time after this was reported. I think it's safe to call this library deprecated/no longer maintained.

**Comment by mathiasburger** [comment]
Ubuntu does not ship with python2 anymore and gimp won't have the python2 interpreter that it uses. You need to follow the same setup as on the CI, e.g. https://github.com/mabu-github/pgimp/blob/master/test/envs/linux/ubuntu/20.04/Dockerfile.
